### ISSUE TITLE
clarification on formula

### ISSUE THREAD

**Issue by andreapago** [sjtrny/Dark-Channel-Haze-Removal#1]
@sjtrny 

Hi Stephen, very nice code. I am trying to reproduce this method in R. I have a small question I came across while porting: in get_atmosphere.m 

```
n_search_pixels = floor(n_pixels * 0.01);
```

In the reference paper (http://research.microsoft.com/en-us/um/people/jiansun/papers/Dehaze_CVPR2009.pdf) it is stated 

> 0.1% bright-est pixels in the dark channel. These pixels are most haze-opaque (bounded by yellow lines in Figure6(b)).

It doesn't make much difference (I would say) at the end since you take the average of the accumulated pixels, but I was wondering why you used 1% instead of 0.1%.

Many thanks in advance.

**Comment by sjtrny** [comment]
@andreapago Thanks for your interest!

I suspect that I made a typo or misread the paper. I will correct the code when I commit with some new changes shortly.

**Comment by andreapago** [comment]
@sjtrny 
Hello Stephen, thanks for your reply.
Interesting, are you adding new features or ideas? It would be nice to know your new ideas on the topic.
Cheers.

**Comment by sjtrny** [comment]
It's only a minor change. Adding some new functions that use the Guided Filter instead of solving the large linear system to save time.

**Comment by andreapago** [comment]
Cool, thanks for sharing!
