### ISSUE TITLE
Is this the original code of He Kaiming?

### ISSUE THREAD

**Issue by xijinmu** [sjtrny/Dark-Channel-Haze-Removal#3]
Hello, I am honored to read your paper. I would like to ask if this code is the original code of He Keming?

**Comment by sjtrny** [comment]
Hi, sorry I am not the author. This is my own implementation, which has been pieced together from various sources.

**Comment by xijinmu** [comment]
> Hi, sorry I am not the author. This is my own implementation, which has been pieced together from various sources.

Thank you for your careful answer. I really admire the scholar like you who can reply questions to beginners carefully.
