### ISSUE TITLE
Issue of the get_atmoshperic.m

### ISSUE THREAD

**Issue by swuliuyun** [sjtrny/Dark-Channel-Haze-Removal#4]
In your get_atmoshpere.m code, you first select top 1% percent brightest pixels in the dark channel. Then, the average intensity of these pixels in the original input hazy images is regarded as the atmospheric light. However, this does not match the original paper (Single Image Haze Removal Using Dark Channel Prior) that illustrates the atmospheric light is considered as the pixels with highest intensity (mean intensity of each channel) in the input hazy image I are selected the atmosphere light.

Therefore, I provide my revised code based on your given code.
function atmosphere = get_atmosphere(image, dark_channel)

[m, n, ~] = size(image);
n_pixels = m * n;

n_search_pixels = floor(n_pixels * 0.001);

dark_vec = reshape(dark_channel, n_pixels, 1);

image_vec = reshape(image, n_pixels, 3);

[~, indices] = sort(dark_vec, 'descend');

% accumulator = zeros(1, 3);

% for k = 1 : n_search_pixels
%     accumulator = accumulator + image_vec(indices(k),:);
% end
% 
% atmosphere = accumulator / n_search_pixels;

atmosphere_search_pixels = zeros(n_search_pixels,3);
for k=1 : n_search_pixels
    atmosphere_search_pixels(k,:) = image_vec(indices(k),:);
end

[~, top_intensity_indices] = sort(mean(atmosphere_search_pixels,2), 'descend');
atmosphere = atmosphere_search_pixels(top_intensity_indices(1),:);

end

**Comment by sjtrny** [comment]
Hi @swuliuyun thanks for discovering this. I don't have MATLAB currently installed. Give me a few days to get back to you after I test it.

**Comment by sjtrny** [comment]
Hi @swuliuyun, it looks like your code does the following:

1. Collect pixels from `I` corresponding to brightest images in the dark channel
2. Take mean of each of these pixels to **estimate their intensity**
3. Pick **the single most intense pixel**

My main concerns are that:
- estimating intensity by the mean of RGB values may not be ideal
- the paper seems to indicate that more than one pixel is used, see quote below

> Among these pixels, the pixels with highest intensity in the input image `I` is selected as the atmospheric light

In the case that multiple pixels have the same and greatest intensity then I think we should be taking the mean.

**Comment by swuliuyun** [comment]
The mean intensity of each pixel in three channels can denote the Value-intensity. You can refer the details from RGB color space to HSV color space. The V-channel is the mean intensity of each channel. I think this can well represent the text “Among these pixels, the pixels with highest intensity in the input image I is selected as the atmospheric light” of the original paper. 

Anyway, in your previous atmosphere.m code, you first accumulate the intensity of these selected pixels and consider the average intensity of these pixels, which does not align with the implementation details in original paper.

**Comment by swuliuyun** [comment]
> Hi @swuliuyun, it looks like your code does the following:
> 
> 1. Collect pixels from `I` corresponding to brightest images in the dark channel
> 2. Take mean of each of these pixels to **estimate their intensity**
> 3. Pick **the single most intense pixel**
> 
> My main concerns are that:
> 
> * estimating intensity by the mean of RGB values may not be ideal
> * the paper seems to indicate that more than one pixel is used, see quote below
> 
> > Among these pixels, the pixels with highest intensity in the input image `I` is selected as the atmospheric light
> 
> In the case that multiple pixels have the same and greatest intensity then I think we should be taking the mean.


The mean intensity of each pixel in three channels can denote the Value-intensity. You can refer the details from RGB color space to HSV color space. The V-channel is the mean intensity of each channel. I think this can well represent the text “Among these pixels, the pixels with highest intensity in the input image I is selected as the atmospheric light” of the original paper. 

Anyway, in your previous atmosphere.m code, you first accumulate the intensity of these selected pixels and consider the average intensity of these pixels, which does not align with the implementation details in original paper.

**Comment by sjtrny** [comment]
> which does not align with the implementation details in original paper.

I'm not disagreeing with your overall message and intent. But while we're here I think it would be good to get it right, rather than just a partial fix.

> The mean intensity of each pixel in three channels can denote the Value-intensity. 

It's not quite that simple. See here for a discussion https://computergraphics.stackexchange.com/questions/5085/light-intensity-of-an-rgb-value

>  I think this can well represent the text 

I think you missed my point, which is that multiple pixels could have the same intensity value but different RGB values.

**Comment by swuliuyun** [comment]
> > which does not align with the implementation details in original paper.
> 
> I'm not disagreeing with your overall message and intent. But while we're here I think it would be good to get it right, rather than just a partial fix.
> 
> > The mean intensity of each pixel in three channels can denote the Value-intensity.
> 
> It's not quite that simple. See here for a discussion https://computergraphics.stackexchange.com/questions/5085/light-intensity-of-an-rgb-value
> 
> > I think this can well represent the text
> 
> I think you missed my point, which is that multiple pixels could have the same intensity value but different RGB values.

I

**Comment by swuliuyun** [comment]
I know your point. I agree that multiple pixels could have the same intensity value but different RGB values.

However, the original paper states that among these pixels, the pixels with “highest” intensity in the input image I is selected as the atmospheric light. Therefore, we require to search a rule to obtain the highest intensity. 

Based on the above consideration, the V-channel in HSV color space (V=(R+G+B)/3) can be considered to represent the intensity. 

Indeed, multiple pixels could have the same intensity value but different RGB values. We can select one of these pixels or average these pixels to represent the atmospheric light value. 

However, in your original code, you directly average the intensity of input image I with top 1% brightness in the dark channel. There exist two errors. First, 1% should be corrected as 0.1%. Second, you fail to select the pixels with highest in the input image I.

**Comment by swuliuyun** [comment]
I am very agree the corrected code of get_atmosphere.m. 
 I agree that multiple pixels could have the same intensity value but different RGB values. And the implementation that you average these "highest" pixels in each channel as the final atmospheric light value.

**Comment by sjtrny** [comment]
@swuliuyun Thank you for finding the bug and taking the time to report it!
